# Generated by Django 2.2.6 on 2019-11-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('street', models.CharField(max_length=50)),
                ('apt', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=15)),
                ('zip', models.PositiveIntegerField()),
            ],
        ),
    ]
