# Generated by Django 2.2.6 on 2019-11-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_logins',
            field=models.IntegerField(default=0),
        ),
    ]
