# Generated by Django 2.2.6 on 2019-11-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0002_user_failed_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked_out_until',
            field=models.DateTimeField(default='1970-01-01 12:00'),
        ),
    ]
