# Generated by Django 2.2.6 on 2019-11-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0003_user_locked_out_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locked_out_until',
            field=models.DateTimeField(default='1970-01-01 11:11'),
        ),
    ]
