# Generated by Django 2.2.6 on 2019-11-01 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0004_auto_20191101_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locked_out_until',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
