# Generated by Django 2.2.6 on 2019-11-02 06:04

from django.db import migrations, models
import task3.utils


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0005_auto_20191101_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=task3.utils.generate_salt, max_length=16),
        ),
    ]
