# Generated by Django 2.2.6 on 2019-11-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task3', '0007_auto_20191109_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
